apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  selector:
    app: hello-world
  type: {{ .Values.serviceType }}
  ports:
  - port: {{ .Values.port }}
    targetPort: {{ .Values.port }}
