# Default application image details
image:
  repository: vanshul16/bansiraassesment
  tag: latest

# Deployment configuration
replicaCount: 1
resources:
  limits:
    memory: "100Mi"
    cpu: "100m"
  requests:
    memory: "50Mi"
    cpu: "50m"

# Service configuration
serviceType: ClusterIP
port: 80
